apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: expense-tracker
resources:
- serviceaccounts.yaml
- clusterrole-promtail.yaml
- loki-service.yaml
- loki-headless-service.yaml
- loki-memberlist-service.yaml
- loki-secret.yaml
- loki-promtail-secret.yaml
- loki-statefulset.yaml
- loki-promtail-daemonset.yaml
