apiVersion: v1
kind: ConfigMap

metadata:
  name: expense-tracker-config
  namespace: expense-tracker

data:
  FLASK_ENV: "development"
  LOG_LEVEL: "DEBUG"

  BACKEND_HOST: "backend-service"
  BACKEND_PORT: "5000"