apiVersion: v1
kind: Secret
metadata:
  name: expense-tracker-secret
  namespace: expense-tracker
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL2V4cGVuc2VfdXNlcjpleHBlbnNlX3Bhc3NAcG9zdGdyZXMtc2VydmljZTo1NDMyL2V4cGVuc2VfdHJhY2tlcg==
  DATABASE_PASSWORD: ZXhwZW5zZV9wYXNz