apiVersion: v1
kind: Service

metadata:
  name: postgres
  namespace: expense-tracker

  labels:
    app: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: expense-tracker

spec:
  type: ClusterIP

  selector:
    app: postgres

  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP